name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        ls -last
        pip install -r requirements.txt

    - name: Docker-compose up before tests
      run: docker-compose up -d

    - name: Run Tests
      id: test
      run: python3 app/test.py
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      env:
        IMAGE_TAG: main-${{ github.sha:0:7 }}-${{ github.run_number }}
      if: steps.test.outcome == 'success'
      run: |
        docker build -t shayts/noteapp:$IMAGE_TAG .
        docker push shayts/noteapp:$IMAGE_TAG
